# Generated by Django 4.0.6 on 2022-07-20 03:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('url', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=48)),
                ('genus', models.CharField(max_length=200)),
                ('caption', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Category List',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(max_length=2000)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='den.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='den.location')),
            ],
        ),
    ]
