import Head from "next/head";
// import "../assets/scripts/cursor.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zurupango</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Zurupango</h1>
    </>
  );
}
