import Head from "next/head";
// import "../assets/scripts/cursor.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zurupango</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="hero">
        <div className="banner">
          <div className="content">
            <h1 className="title">VISIT THE DEN</h1>
            <h1 className="subtitle">OF AFRICAS'</h1>
            <h1 className="title">BIGGEST CATS</h1>
          </div>
        </div>
      </section>
    </>
  );
}
