import axios from 'axios';
import Head from 'next/head';
import { CatCard } from '../components';

export default function Home({ cats }) {
	return (
		<>
			<Head>
				<title>Zurupango</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<section id='hero'>
				<div className='banner'>
					<div className='content'>
						<h1 className='title'>VISIT THE DEN</h1>
						<h1 className='subtitle'>OF AFRICAS'</h1>
						<h1 className='title'>BIGGEST CATS</h1>
					</div>
				</div>
			</section>
			<section id='section'>
				<h1 className='stitle'>Latest shots</h1>
				<div id='latest'>
					{cats?.map((cat) => (
						<CatCard key={cat.id} cat={cat} />
					))}
				</div>
			</section>
		</>
	);
}

export async function getServerSideProps() {
	const catsRes = await axios.get(`https://zurupango.herokuapp.com/api/cats/`);
	const cats = catsRes.data;

	return {
		props: { cats },
	};
}
